---

variables:
  CHECK_IMAGE: 'python:3.10-alpine'


include:
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'

  - project: 'saltbox/ci-lib'
    file: 'mirror-repo.yml'

  - project: 'saltbox/ci-lib'
    file: 'close-github-pr.yml'


stages:
  - lint
  - test
  - build


.check:
  stage: lint
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
  image: '$CHECK_IMAGE'
  before_script: 'pip3 install -e .[dev]'
  cache:
    paths:
      - '.cache/pip/'


Ruff:
  extends: .check
  script: 'ruff check .'


MyPy:
  extends: .check
  script: 'mypy .'


Mirror Repository:
  extends: .mirror-repo
  stage: build


Check for GitHub PR to close:
  extends: .close-github-pr
  stage: build
